# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_book_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
