# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20180417_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books_published',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
    ]
